networks:
  default:
    driver: bridge
    name: roboshop
    external: true # I created the netwrok already using docker netwrok create roboshop manually, hence external true, else if you want it to create then make it false

services:
  mongodb:
    image: joindevops0425/mongodb
    container_name: mongodb

  catalogue:
    image: joindevops0425/catalogue
    container_name: catalogue
    depends_on: 
      - mongodb

  redis: 
    image: redis:7.0
    container_name: redis
  
  user: 
    image: joindevops0425/user
    container_name: user
    depends_on: 
      - redis
      - mongodb
  
  cart:
    image: joindevops0425/cart
    container_name: cart
    depends_on: 
      - catalogue
      - redis

  mysql:
    image: joindevops0425/mysql
    container_name: mysql

  shipping: 
    image: joindevops0425/shipping
    container_name: shipping
    depends_on: 
      - mysql
      - cart

  rabbitmq: 
    image: rabbitmq:3
    container_name: rabbitmq
    environment: 
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    
  payment: 
    image: joindevops0425/payment
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOS: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123 
    depends_on: 
      - rabbitmq
      - cart
      - user

  frontend:
    image: joindevops0425/frontend
    container_name: frontend
    ports: 
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - shipping
      - payment